[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt --no-cache-dir"]

[phases.build]
cmds = []

[start]
cmd = "cd admin_web && python flask_app.py"

