[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [". /opt/venv/bin/activate && pip install --upgrade pip", ". /opt/venv/bin/activate && pip install -r requirements.txt --no-cache-dir"]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && cd admin_web && python flask_app.py"

